@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
participant "Organization Employee" as ADM
participant "CreateJobUI" as UI
participant "JobRepository" as Repo
participant "Job" as Job

activate ADM

ADM -> UI : Step 1: Interaction - Request to create a new job
activate UI

UI -> UI : Step 2: Requests data (jobName) - Display form for input
UI -> UI : Step 3: Types requested data (jobName) - Temporarily keeps input
UI -> UI : Step 4: Shows all data and requests confirmation - Display all information before submitting
UI -> Repo : Step 5: Confirm data - Save new job and validate data (if necessary)
Repo -> Job : Save inputed data
Job -> Job : Validate mandatory data
Repo -> Job : Validate globally (check for duplicate data)
Repo -> Job : Save the created job
UI -> UI : Step 5: Display operation success - Inform operation success

deactivate UI
deactivate ADM
@enduml
