@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Organization\nEmployee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to list the vehicles needing the check up
    activate System

        System --> Employee : displays list successfully
    deactivate System

@enduml