@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Green Space\nManager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : Asks to list the green spaces managed by me
    activate System
        System --> HRM : Displays list of green spaces


@enduml