@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

left to right direction

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Employe {
    name
    role
    phoneNumber
    email
}

class HRM {
    ...
}

class VFM {
    ...
}

class GSM {
    ...
}

class GSU {
     name
     phoneNumber
}

class Collaborator {
    name
    birthDate
    admissionDate
    address
    phoneNumber
    email
    taxpayerNumber
    BINumber
}

class Garden {
    ...
}

class MediumSizePark {
    ...
}

class LargePark {
    ...
}

class Parks {
}

class Task {
    name
    description
    duration
    cost
}

class Agenda {
    dateOfCreation
    state
}

class Vehicle {
    plateID
    model
    type
    tare
        gross Weight
        current Km
         register Date
         acquisition Date
         maintenance/Checkup Frequency (in Kms)
         last maintenance date
         next maintenance date
}

class Machine {
    name
    description
}

class Equipment {
    name
    description
}

class Portal {
    reports
    comments
}

class CheckUp {
    plateID
    date
    kmAtCheckup
}

class Job {
    name
}

class Team {
    numberColaborators
    skils
}

class Skill {
    name
}




Organization "1" -- "*" Employe : has
Organization "1" -- "*" Parks : owns

Employe "1" -- "*" Task : creates
Employe "1" -- "1" GSM : can be
Employe "1" -- "1" HRM : can be
Employe "1" -- "1" VFM : can be

HRM "1" -- "*" Collaborator : creates
HRM "1" -- "*" Team : generate
HRM "1" -- "*" Job : creates
HRM "1" -- "*" Skill : creates

Collaborator "1" -- "1" Job : has
Collaborator "1" -- "1" Team : is a member of
Collaborator "1" -- "*" Skill : possesses
Collaborator "1" -- "*" Task : is assigned to
Collaborator "1" -- "*" Vehicle : drives
Collaborator "1" -- "*" Machine : uses
Collaborator "1" -- "*" Equipment : uses

Team "1" -- "*" Skill : has
Team "1" -- "*" Task : do
Team "1" -- "*" Machine : utilizes
Team "1" -- "*" Equipment : utilizes


Agenda "1" -- "*" Task : has

GSU "1" -- "0.*" Portal : writes to

Parks "*" -- "*" Garden : can be
Parks "*" -- "*" MediumSizePark : can be
Parks "*" -- "*" LargePark : can be
Parks "1" -- "0.*" GSU : has

VFM "1" -- "*" CheckUp: register
VFM "1" -- "*" Vehicle: manages

GSM "1" -- "1" Portal: manages and reads
GSM "1" -- "*" Parks: creats

Vehicle "1" -- "*" CheckUp : undergoes

@enduml
