@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Green Space Manager (GSM)" as GSM
participant "RegisterGreenSpaceUI" as UI
participant "RegisterGreenSpaceController" as CTRL
participant "Repositories" as RepositorySingleton
participant "repositories : Repositories" as PLAT
participant "greenSpaceRepository : GreenSpaceRepository" as GreenSpaceRepository
participant "ApplicationSession" as _APP
participant "appSession : ApplicationSession" as APP
participant "currentSession : UserSession" as SESSAO
participant "greenSpace : GreenSpace" as GREENSPACE

activate GSM

    GSM -> UI : requests to register green space
    activate UI

        UI --> GSM : prompts for required fields (e.g., name, area, type)
    deactivate UI

    GSM -> UI : provides green space details (name, area, type)
    activate UI

        UI -> CTRL : registerGreenSpace(name, area, type)
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getGreenSpaceRepository()
            activate PLAT

                PLAT --> CTRL : greenSpaceRepository
            deactivate PLAT

            CTRL -> _APP: getInstance()
            activate _APP
                _APP -> CTRL: appSession
            deactivate _APP

            CTRL -> APP: getCurrentSession()
            activate APP

                APP --> CTRL: currentSession
            deactivate APP

            CTRL -> SESSAO: email = getUserEmail()
            activate SESSAO

                SESSAO --> CTRL: email
            deactivate SESSAO

            CTRL -> GREENSPACE : new GreenSpace(name, area, type)
            activate GREENSPACE

                GREENSPACE -> GREENSPACE : validate details
                GREENSPACE -> greenSpaceRepository : registerGreenSpace(greenSpaceRepository)
                deactivate GREENSPACE

            deactivate CTRL

            CTRL --> UI : confirms successful green space registration
    deactivate UI

    UI --> GSM : confirms successful green space registration

deactivate GSM

@enduml
