@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Green Space Manager (GSM)" as GSM
participant "RegisterGreenSpaceUI" as UI
participant "RegisterGreenSpaceController" as CTRL
participant "Repositories" as RepositorySingleton
participant "repositories : Repositories" as PLAT
participant "ApplicationSession" as _APP
participant "appSession : ApplicationSession" as APP
participant "currentSession : UserSession" as SESSAO
participant "organizationRepository : OrganizationRepository" as OrganizationRepository
participant "organization : Organization" as ORGANIZATION
participant "greenSpaceRepository : GreenSpaceRepository" as GreenSpaceRepository
participant "greenSpace : GreenSpace" as GREENSPACE

activate GSM

    GSM -> UI : requests to register green space
    activate UI

        UI --> GSM : prompts for required fields (e.g., name, area, type)
    deactivate UI

    GSM -> UI : provides green space details (name, area, type)
    activate UI

        UI -> CTRL : registerGreenSpace(name, area, type)
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getOrganizationRepository()
            activate PLAT

                PLAT --> CTRL : organizationRepository
            deactivate PLAT

            CTRL -> _APP: getInstance()
            activate _APP
                _APP -> CTRL: appSession
            deactivate _APP

            CTRL -> APP: getCurrentSession()
            activate APP

                APP --> CTRL: currentSession
            deactivate APP

            CTRL -> SESSAO: email = getUserEmail()
            activate SESSAO

                SESSAO --> CTRL: email
            deactivate SESSAO

            CTRL -> OrganizationRepository : getOrganizationByEmployeeEmail(email)
            activate OrganizationRepository

                OrganizationRepository --> CTRL : organization
            deactivate OrganizationRepository

            CTRL -> PLAT : getGreenSpaceRepository()
            activate PLAT

                PLAT --> CTRL : greenSpaceRepository
            deactivate PLAT

            CTRL -> ORGANIZATION : createGreenSpace(name, area, type)
            activate ORGANIZATION

                ORGANIZATION -> GREENSPACE : new GreenSpace(name, area, type)
                activate GREENSPACE

                    GREENSPACE -> GREENSPACE : validate details
                    GREENSPACE -> GreenSpaceRepository : registerGreenSpace(greenSpace)
                deactivate GREENSPACE

            deactivate ORGANIZATION

            CTRL --> UI : confirms successful green space registration
    deactivate UI

    UI --> GSM : confirms successful green space registration

deactivate GSM

@enduml
