@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor yellow
}

left to right direction

rectangle "System Actors" as actors {
    actor HRM as "Human Resources Manager (HRM)"
    actor FM as "Fleet Manager (FM)"

}

rectangle "Use Cases" as usecases{
    usecase US01 as "Register Skills"
    usecase US02 as "Register Job"
    usecase US03 as "Register Collaborator"
    usecase US04 as "Assign Skills to Collaborator"
    usecase US05 as "Generate Team Proposal"
    usecase US06 as "Register Vehicle"
    usecase US07 as "Register Vehicle's Check-up"
    usecase US08 as "List Vehicles Needing Check-up"
}

HRM --> US01
HRM --> US02
HRM --> US03
HRM --> US04
HRM --> US05

FM --> US06
FM --> US07
FM --> US08

@enduml
