@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Green Space\nManager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : Asks to list the tasks assign to me
    activate System
        System --> GSM : Displays list of taskss

    deactivate System

@enduml