
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) for US002 - Assign a Team to an Entry in the Agenda

autonumber

actor "Green Spaces Manager" as GSM
participant ":System" as System

activate GSM

GSM -> System : requests to assign a team to an agenda entry
activate System
System --> GSM : requests selection of an agenda entry

deactivate System

GSM -> System : selects an agenda entry
activate System
System --> GSM : requests selection of a team

deactivate System

GSM -> System : selects a team
activate System
System --> GSM : sends success or error message

System --> GSM : informs team members about the assignment

deactivate System

@enduml