@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Green Space Manager" as USER
participant "ToDoListUI" as UI
participant "ToDoListController" as CTRL
participant "Repositories" as Repositories
participant "ToDoListRepository" as ToDoListRepository
participant "ApplicationSession" as APP
participant "UserSession" as SESSION
participant "ToDoList" as TODOLIST

activate USER

    USER -> UI : requests to add new to-do list entry
    activate UI

        UI --> USER : prompts for required fields (e.g., taskDescription, urgency, expectedDuration, greenspaceName, status)
    deactivate UI

    USER -> UI : provides to-do list details (taskDescription, urgency, expectedDuration, greenspaceName, status, email)
    activate UI

        UI -> CTRL : createToDoListEntry(taskDescription, urgency, expectedDuration, greenspaceName, status, email)
        activate CTRL

            CTRL -> Repositories : getInstance()
            activate Repositories

                Repositories --> CTRL : toDoListRepository
            deactivate Repositories

            CTRL -> APP: getInstance()
            activate APP

                APP -> CTRL: getCurrentSession()
            deactivate APP

            CTRL -> SESSION: getUserEmail()
            activate SESSION

                SESSION --> CTRL: email
            deactivate SESSION

            CTRL -> TODOLIST : new ToDoList(taskDescription, urgency, expectedDuration, greenspaceName, status, email)
            activate TODOLIST

                TODOLIST -> TODOLIST : validate details
                TODOLIST -> ToDoListRepository : add(TODOLIST)
            deactivate TODOLIST

            CTRL --> UI : confirms successful to-do list entry creation
    deactivate CTRL

    UI --> USER : confirms successful to-do list entry creation

deactivate USER

@enduml
