@startuml

'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as ADM
participant ":AssignSkillUI" as UI
participant ":AssignSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "SkillRepository:\nSkillRepository" as SkillRepository
participant "EmployeeRepository:\nEmployeeRepository" as EmployeeRepository
participant "collaborator\n:Employee" as COLLABORATOR

activate ADM

    ADM -> UI : requests to assign skills to collaborator

    activate UI

        UI -> CTRL** : assignSkillsToCollaborator

        UI -> CTRL : getCollaborators()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getEmployeeRepository()
            activate PLAT

                PLAT --> CTRL : employeeRepository
            deactivate PLAT

            CTRL -> EmployeeRepository : getCollaborators()
            activate EmployeeRepository

                EmployeeRepository --> CTRL : collaboratorList
            deactivate EmployeeRepository

            CTRL --> UI : collaboratorList
        deactivate CTRL

        UI --> ADM : displays list of collaborators
    deactivate UI

    ADM -> UI : selects a collaborator
    activate UI

        UI --> ADM : requests action (add skill, remove skill)
    deactivate UI

    ADM -> UI : confirms action
    activate UI

        UI -> CTRL : getCollaboratorSkills(collaboratorId)
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getEmployeeRepository()
            activate PLAT

                PLAT --> CTRL : employeeRepository
            deactivate PLAT

            CTRL -> EmployeeRepository : getCollaboratorSkills(collaboratorId)
            activate EmployeeRepository

                EmployeeRepository --> CTRL : collaboratorSkills
            deactivate EmployeeRepository

            CTRL --> UI : collaboratorSkills
        deactivate CTRL

        UI -> CTRL : getSkills()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getSkillRepository()
            activate PLAT

                PLAT --> CTRL : skillRepository
            deactivate PLAT

            CTRL -> SkillRepository : getSkills()
            activate SkillRepository

                SkillRepository --> CTRL : skillList
            deactivate SkillRepository

            CTRL --> UI : skillList
        deactivate CTRL

        UI --> ADM : displays list of collaborator's skills with options to add or remove skills
    deactivate UI

    ADM -> UI : selects to add a skill
    activate UI

        UI --> ADM : requests skill to add
    deactivate UI

    ADM -> UI : select skill to add
    activate UI

        UI --> ADM : confirms skill to add
    deactivate UI

    ADM -> UI : confirms to add skill
    activate UI

        UI -> CTRL : addSkillToCollaborator(collaboratorId, skillName)
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getEmployeeRepository()
            activate PLAT

                PLAT --> CTRL : employeeRepository
            deactivate PLAT

            CTRL -> EmployeeRepository : addSkillToCollaborator(collaboratorId, skillName)
            activate EmployeeRepository

                EmployeeRepository --> CTRL : result
            deactivate EmployeeRepository

            CTRL --> UI : result
        deactivate CTRL

        UI -> CTRL : getCollaboratorSkills(collaboratorId)
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getEmployeeRepository()
            activate PLAT

                PLAT --> CTRL : employeeRepository
            deactivate PLAT

            CTRL -> EmployeeRepository : getCollaboratorSkills(collaboratorId)
            activate EmployeeRepository

                EmployeeRepository --> CTRL : collaboratorSkills
            deactivate EmployeeRepository

            CTRL --> UI : collaboratorSkills
        deactivate CTRL

        UI --> ADM : displays updated list of collaborator's skills
    deactivate UI

deactivate ADM

@enduml
