@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "SkillRepository:\nSkillRepository" as SkillRepository

autonumber 15
-> CTRL : getSkills()

autonumber 15.1
activate CTRL
    group Get Skills
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton
            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton
        CTRL -> PLAT : getSkillRepository()
        activate PLAT
            PLAT --> CTRL : skillRepository
        deactivate PLAT
        CTRL -> SkillRepository : getSkills()
        activate SkillRepository
            SkillRepository --> CTRL : skillList
        deactivate SkillRepository
    end

    autonumber 16
    <-- CTRL : skillList
deactivate CTRL
@enduml
