@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":ListGreenSpacesUI" as UI
participant "ConfigReader:\nConfigReader" as ConfigReader

activate UI

        UI -> ConfigReader : readSortingAlgorithm()
        activate ConfigReader

            ConfigReader --> UI : sortingAlgorithm
        deactivate ConfigReader

deactivate UI

@enduml
