@startuml

'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam linetype orto

skinparam classAttributeIconSize 0


class GreenSpace {
    - String name
    - double area
    - GreenSpaceType type
    - String email

    + String getName()
    + double getArea()
    + GreenSpaceType getType()
    + String getEmail()
    + void displayDetails()
}
class Organization {
    - name: String
    - website: String
    - phone: String
    - email: String
    - vatNumber: String
    - List<Employee> employees
    - List<Task> tasks

    + Organization(vatNumber: String)
    + boolean employs(Employee employee)
    + Optional<Task> createTask(String reference, String description, String informalDescription, String technicalDescription, int duration, double cost, TaskCategory taskCategory, Employee employee)
    + boolean anyEmployeeHasEmail(String email)
    + boolean addEmployee(Employee employee)
    + Organization clone()
}
class GreenSpaceRepository {
    - List<GreenSpace> greenSpaces

    + void addGreenSpace(GreenSpace greenSpace)
    + List<GreenSpace> getGreenSpaces()
    + List<GreenSpace> findByUserEmail(String userEmail)
}
class OrganizationRepository {
    - organizations: List<Organization>

    + Optional<Organization> getOrganizationByEmployee(Employee employee)
    + Optional<Organization> getOrganizationByEmployeeEmail(String email)
    + Optional<Organization> add(Organization organization)
}

class RegisterGreenSpaceController {
    + List<GreenSpace> getAllGreenSpaces()
}

class ListGreenSpacesUI {
    + ListGreenSpacesUI(String userEmail)
    + void run()
}


class Repositories {
    - GreenSpaceRepository greenSpaceRepository

    + GreenSpaceRepository getGreenSpaceRepository()
}
class ApplicationSession {
    + static getInstance()
    + getCurrentSession()
}

class UserSession {
    + getUserEmail()
}
Repositories -> Repositories : instance

ListGreenSpacesUI .> RegisterGreenSpaceController
ApplicationSession -> ApplicationSession : instance
ApplicationSession --> "1" UserSession : userSession
RegisterGreenSpaceController ..> ApplicationSession
UserSession ..> RegisterGreenSpaceController
RegisterGreenSpaceController .> Repositories : repositories

Repositories -> "1" GreenSpaceRepository
Repositories -> "1" OrganizationRepository

OrganizationRepository ..> Organization : organization
Organization ..> GreenSpace : asks to list
RegisterGreenSpaceController ..> Organization

GreenSpaceRepository --> GreenSpace


@enduml
