@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":ListGreenSpacesUI" as UI
participant ":RegisterGreenSpaceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "GreenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository

activate UI

        UI -> CTRL : getAllGreenSpaces()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getGreenSpaceRepository()
            activate PLAT

                PLAT --> CTRL : greenSpaceRepository
            deactivate PLAT

            CTRL -> GreenSpaceRepository : getGreenSpaces()
            activate GreenSpaceRepository

                GreenSpaceRepository --> CTRL : greenSpacesList
            deactivate GreenSpaceRepository

            CTRL --> UI : greenSpacesList
        deactivate CTRL

deactivate UI

@enduml
