@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) for US022 - Add a New Entry in the Agenda

autonumber

actor "Green Spaces Manager" as GSM
participant ":System" as System


activate GSM

GSM -> System : requests to add a new entry in the Agenda
activate System
System --> GSM : requests selection of a green space

deactivate System

GSM -> System : selects a green space
activate System
System --> GSM : requests selection of a to-do list entry

deactivate System

GSM -> System : selects a to-do list entry
activate System
System --> GSM : requests starting date

deactivate System

GSM -> System : provides starting date
activate System
System --> GSM : requests status (Planned, Postponed, Canceled, Done)

deactivate System

GSM -> System : selects status
activate System
System --> GSM : Success or error message

deactivate System

@enduml