@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignSkillController" as CTRL

autonumber 15
-> CTRL : removeSkillFromCollaborator(collaboratorId, skillName)

autonumber 15.1
activate CTRL
    group Remove Skill From Collaborator
        CTRL -> EmployeeRepository : removeSkillFromCollaborator(collaboratorId, skillName)
        activate EmployeeRepository
            EmployeeRepository --> CTRL : result
        deactivate EmployeeRepository
    end

    autonumber 16
    <-- CTRL : result
deactivate CTRL
@enduml
