@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "HR Manager" as HRM
participant ":GenerateTeamProposalUI" as UI
participant ":GenerateTeamProposalController" as CTRL
participant "organization\n:Organization" as ORG

activate HRM
HRM -> UI : Asks to create a new team proposal
activate UI

UI -> CTRL : create
activate CTRL

deactivate UI
deactivate CTRL
deactivate HRM

@enduml
