@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Organization {
      name
      vatNumber
      website
      phoneNumber
      email
}


class Employe {
    name
    role
    phoneNumber
    email
}

class HRM {
    ...
}

class Collaborator {
    name
    birthDate
    admissionDate
    address
    phoneNumber
    email
    taxpayerNumber
    BINumber
}

class Job {
    name
    description
}




Organization "1" - "*" Employe : has >
Employe "1" -- "1" HRM : can be
HRM "1" -- "*" Collaborator : creates
Collaborator "1" -- "1" Job : has

@enduml