@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)- US005

autonumber

actor "HDM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to generate a new team
    activate System

        System --> Employee : requests data (i.e. number of employes, skills needed))
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : generate a team
    deactivate System

    Employee -> System : confirms data
    activate System



        System --> Employee : displays operation success
    deactivate System

@enduml